# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=17)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('following', models.ManyToManyField(to='tweetapp.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='createby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createby', to='tweetapp.userinfo'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='like',
            field=models.ManyToManyField(to='tweetapp.userinfo'),
        ),
    ]
